name: 'runCI Action'

description: 'Action to run CI builds'

inputs:
  PROJECT_NAME:
    required: true
  CC:
    required: true
  DOCKER_IMAGE:
    required: true
  TPM2TOOLS_BRANCH:
    required: false
  TPM2TSS_BRANCH:
    required: false
  BASE_REF:
    required: false
  SCANBUILD:
    required: false
  TEST_TCTI_CONFIG:
    required: false
  WITH_CRYPTO:
    required: false
  WITH_TCTI:
    required: false
  ENABLE_COVERAGE:
    required: false
  GEN_FUZZ:
    required: false
  CXX:
    required: false
  GIT_FULL_CLONE:
    required: false
  MAKE_TARGET:
    required: false
  ENABLE_FUZZING:
    required: false
  TPM2_TSS_VERSION:
    required: false
  MULTIARCH_BUILD:
    required: false

runs:
  using: composite
  steps:
    - name: Launch Container
      env:
        TPM2TOOLS_BRANCH: ${{ inputs.TPM2TOOLS_BRANCH }}
        TPM2TSS_BRANCH: ${{ inputs.TPM2TSS_BRANCH }}
        CC: ${{ inputs.CC }}
        DOCKER_IMAGE: ${{ inputs.DOCKER_IMAGE }}
        PROJECT_NAME: ${{ inputs.PROJECT_NAME }}
        BASE_REF: ${{ inputs.BASE_REF }}
        SCANBUILD: ${{ inputs.SCANBUILD }}
        TEST_TCTI_CONFIG: ${{ inputs.TEST_TCTI_CONFIG }}
        WITH_CRYPTO: ${{ inputs.WITH_CRYPTO }}
        WITH_TCTI: ${{ inputs.WITH_TCTI }}
        ENABLE_COVERAGE: ${{ inputs.ENABLE_COVERAGE }}
        GEN_FUZZ: ${{ inputs.GEN_FUZZ }}
        CXX: ${{ inputs.CXX }}
        GIT_FULL_CLONE: ${{ inputs.GIT_FULL_CLONE }}
        MAKE_TARGET: ${{ inputs.MAKE_TARGET }}
        ENABLE_FUZZING: ${{ inputs.ENABLE_FUZZING }}
        TPM2_TSS_VERSION: ${{ inputs.TPM2_TSS_VERSION }}
        MULTIARCH_BUILD: ${{ inputs.MULTIARCH_BUILD }}
      run: ${{ github.action_path }}/../scripts/ci.sh
      shell: bash
